// <auto-generated />
namespace HDA.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Pharmacy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pharmacy));
        
        string IMigrationMetadata.Id
        {
            get { return "201909091135544_Pharmacy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
