// <auto-generated />
namespace HDA.Core.Migrations.HDACore
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DiagnosisTotals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiagnosisTotals));
        
        string IMigrationMetadata.Id
        {
            get { return "201909240831256_DiagnosisTotals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
